### ISSUE TITLE
typeof undefined

### ISSUE THREAD

**Issue by zlatanvasovic** [kangax/jscritic#10]
L1 of `jscritic.js` has something a bit weird. I think that this is bad way to check is the something defined: `typeof process !== 'undefined'`. `process !== undefined` should be enough. Correct me if I'm wrong.

**Comment by chris-l** [comment]
@ZDroid : `undefined` is a global variable.
In older versions of ecmascript, before version 5, `undefined` could be overwritten to have a different value.
Since ecmascript 5, its now set as an read-only value. 
For instance, I read that on Chrome 16 `undefined` was still writable.

So, in a browser were it is writable, it seems that doing `process !== undefined` is less safe than `typeof process !== 'undefined'`.

**Comment by zlatanvasovic** [comment]
@chris-l Sounds legit. Waiting @kangax to reply.

**Comment by kangax** [comment]
Yep. What Christopher said.
